### ISSUE TITLE
Duplicate builds when triggering ofborg before the eval

### ISSUE THREAD

**Issue by fgaz** [NixOS/ofborg#227]
See for example https://github.com/NixOS/nixpkgs/pull/45329 and https://github.com/NixOS/nixpkgs/pull/45372

**Comment by grahamc** [comment]
Because you are a known or trusted user, and your commit message started with a valid attribute name followed by a colon, (ie: `testdisk-photorec:`) the evaluation triggered the automatic build feature of OfBorg: https://github.com/nixos/ofborg#automatic-building. Thusly, the first set of builds were due to your request, the second set of builds were due to the commit message being well formed.

**Comment by fgaz** [comment]
Thanks and sorry for bothering you, I was not aware of that feature
