### ISSUE TITLE
Add more rebuild labels, eg. 501-1000

### ISSUE THREAD

**Issue by hedning** [NixOS/ofborg#304]
There's a big difference between a PR which rebuilds ~500 derivations and one that rebuilds several thousand. It would be nice if we could have labels up to at least 5000 I think (though probably no reason not scale it up to 20k, which I believe is around the amount of derivations x86_64-linux has at the moment).

So something like this:
- 501-1000
- 1001-2000
- 2001-5000
- 5001-10000
- 10001+

This would give us a better idea if something actually needs to go to staging.

**Comment by orivej** [comment]
IMHO 500 rebuilds is a good boundary between master and staging. Yes, Hydra can comfortably sustain a 5000 rebuilds PR, but only if it happens about once per day.

**Comment by andir** [comment]
I would very much welcome those new labels. IMO 5k+ or 10k+ is little difference in terms of how it should be handled. It will often be decision that has to be made for each PR.

Just my two cents :-)

**Comment by 7c6f434c** [comment]
I agree that 500 rebuilds is probably a good _default_ boundary (so, the edge of red, the threshold if we ever get branch choice advice from ofBorg); but sometimes a bit more information might be useful (especially when a lot of the rebuilds are known to be cheap, i.e. Python packages, or when the issue fixed in the update needs its impact compared to the rebuild impact).

**Comment by hedning** [comment]
> I agree that 500 rebuilds is probably a good default boundary (so, the edge of red, the threshold if we ever get branch choice advice from ofBorg)

Agreed. The main point is getting some more labels (which seems like low hanging fruit).

**Comment by hedning** [comment]
fixed by #312
