### ISSUE TITLE
Running tests on platforms different from x86_64-linux (e.g. aarch64)

### ISSUE THREAD

**Issue by andir** [NixOS/ofborg#36]
Currently `ofborg` is not running tests on any platform that is not `x86_64-linux`, especially not `aarch64`. According to @grahamc the relevant source code part is:

https://github.com/grahamc/ofborg/blob/ec4d16c21fdcbc9e2620d12efdba0aa06ba2492c/ofborg/src/tasks/build.rs#L74-L77

**Comment by tilpner** [comment]
[ofborg builds for aarch64-linux](https://github.com/NixOS/nixpkgs/pull/33882#pullrequestreview-92054820)

**Comment by grahamc** [comment]
Ah so this ticket is about NixOS tests which are only running on x86_64 right now.

**Comment by grahamc** [comment]
A while ago I added a hack to force tests to only build on x86_64-linux. To do this project properly, we need to:

- [x] deploy this patch https://github.com/NixOS/ofborg/commit/8eb076077aad48566b437ede9331eb30b5adfa9a which makes the hack not necessary
- [x] deploy this patch https://github.com/NixOS/ofborg/compare/tests-on-aarch64 which detects that if the x86_64-linux suffix is present, removes it
- [ ] once all the builders have updated, remove the suffix from https://github.com/NixOS/ofborg/blob/released/ofborg/src/commentparser.rs#L52
- [ ] delete the patch from step 2

Separately we should only run NixOS tests on boxes that say they can. This is important because ofborgs  running in vms can't. To do this:

1. in githubcommentparser dispatch Test jobs to a separate test exchange
2. when builders start up, create a queue to work from and bind it to the build exchange, and the test exchange _only_ if they want to run tests too.

**Comment by grahamc** [comment]
aarch64 is running NixOS tests now: https://logs.nix.gsc.io/?attempt_id=eb55bc98-a3bf-4fde-bd06-8e2372c655d3&key=nixos%2Fnixpkgs.34331

I'm going to leave this ticket open until I can finish up the last two items.

**Comment by grahamc** [comment]
I went ahead and made a PR for both those tasks so I can close this out. These PRs are just housekeeping.
