### ISSUE TITLE
Some PRs trigger: code: 2, kind: NotFound, message: "No such file or directory"

### ISSUE THREAD

**Issue by doronbehar** [NixOS/ofborg#446]
I see [this error](https://gist.github.com/GrahamcOfBorg/709b8b2b85b5d64ff6bdc2f25d0f8f87) on several PRs with seemingly OK syntax:

```
Failed during the setup of executing nix-env: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Examples:

- https://github.com/NixOS/nixpkgs/pull/84004
- https://github.com/NixOS/nixpkgs/pull/84150
- https://github.com/NixOS/nixpkgs/pull/84160

If the PRs themselves have something wrong with them, I think at least the error message could be better?

**Comment by doronbehar** [comment]
There's also [this error](https://github.com/NixOS/nixpkgs/pull/84183#event-3196110875) coming out for me.

**Comment by cole-h** [comment]
This is because ofborg currently propagates IO errors with little-to-no context. The problematic function could be one of these two:

https://github.com/NixOS/ofborg/blob/a87225519e6bd349f67180f2d862f600d437f420/ofborg/src/nixenv.rs#L62
https://github.com/NixOS/ofborg/blob/a87225519e6bd349f67180f2d862f600d437f420/ofborg/src/nixenv.rs#L69

because any `std::io::Error` gets transformed to the local `Error` enum via this line:

https://github.com/NixOS/ofborg/blob/a87225519e6bd349f67180f2d862f600d437f420/ofborg/src/nixenv.rs#L124

losing all context. I'm working on a PR for this that should give more context, like what operation actually failed (was it creating the file? Removing it? Writing to it?), but I don't know what other information would be helpful, or even if that other information could be displayed.

---

The internal error tag is when something goes really wrong inside ofborg. Currently, Graham manually removes these (in order to allow himself to investigate the cause, first). Assuming it evals + builds, I would say don't worry about it (unless someone else says otherwise).

**Comment by cole-h** [comment]
The root cause appears to be: if the `nix` invocation fails (like when evaluating), the stats file won't be created (example log: https://gist.github.com/GrahamcOfBorg/9dfb034692a8b8397c6bdc476c6910ec). My follow-up PR at #449 demotes this to a logged warning, and should let it get to the point where ofborg reports an actual evaluation error.

EDIT: If this resurfaces, feel free to re-open or open a new issue and ping me. I'll look into it.
