### ISSUE TITLE
Waiting to run this check... cool. now what?

### ISSUE THREAD

**Issue by colemickens** [NixOS/ofborg#585]
So. I've clicked on the checks. I've linked through to the webpage manpage. I've read it. I've read the README.

I still don't know how to do the most common basic task with ofborg, which seems to be authorizing testing on darwin.

> .....passthru.tests on x86_64-darwin Queued — Waiting to run this check... 

What do I do?

**Comment by cole-h** [comment]
Depends. If this is on a recent-ish PR (specifically: any time after last Saturday, 13 November 2021), just wait. The darwin builders should get to it eventually.

*However*, if it's a PR from before then (or if you think it's taking an extraordinary amount of time), tell ofborg to build it again with `@ofborg build` and it should work this time.

Basically, prior to last Friday, ofborg only had 1 darwin builder, and it was slow. So slow, that there were ~3000 builds queued when we added the new builders. Once we added the 3 new x86_64-darwin builders, we decided to push all those builds into a "backup" queue since (and especially during ZHF) it's arguably more important to build newer PRs than older PRs. Once the release is cut and the rate of PRs calms down, we'll look into slowly moving some of those queued builds into the working queue.

I realize this isn't the most ideal situation, but it's what we've got. Sorry, and thanks for bearing with us.

**Comment by colemickens** [comment]
Happy to bear with, it was more of just the disconnect between "there's a bot here" and "I really don't know how to make it do what I want". I guess I should've anticipated that I could just issue a blanket "build" again.

Thanks for all the detail, excited to see things still evolving, thanks for doing the work!

**Comment by cole-h** [comment]
It was a team effort :)

And, for what it's worth, all users can tell ofborg to build on darwin (and it will do so by default, for packages that support it) -- though, this is still subject to change if something untoward ever happens.
