### ISSUE TITLE
vscode label is not automatically set yet

### ISSUE THREAD

**Issue by superherointj** [NixOS/ofborg#614]
`vscode` label is not automatically set yet

**Comment by grahamc** [comment]
should it?

On September 21, 2022, GitHub ***@***.***> wrote:
> vscode label is not automatically set yet
>

—
Reply to this email directly, view it on GitHub
<https://github.com/NixOS/ofborg/issues/614>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAASXLGWS4L53YR26RIXXNTV7N5VVANCNFSM6AAAAAAQSO7NMA>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by superherointj** [comment]
> should it?

I think it should.
Vim, emacs have it.
There is a lot of vscode-extensions packages.
Why not?

Any changes in vscode folder (`pkgs/applications/editors/vscode/`) could trigger it.

**Comment by superherointj** [comment]
There is a label already, OfBorg just doesn't set it automatically yet:

https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%226.topic%3A+vscode%22

**Comment by zowoq** [comment]
> Vim, emacs ..

These labels are managed in the nixpkgs repo: https://github.com/NixOS/nixpkgs/blob/master/.github/labeler.yml

ofborg only does the rebuild count and a couple of others:

https://github.com/NixOS/ofborg/blob/c81e72cc045b635f5b7a8f13c8348f4861418534/ofborg/src/tasks/eval/nixpkgs.rs#L30-L34

**Comment by superherointj** [comment]
Oh. I did not know that. Thanks for clarifying.
